version: '3.7'

volumes:
  logs:

services:
  api:
    image: milkyware/towerbridge:latest
    build:
      context: .
    environment:
      - TZ=Europe/London
      - TOWERBRIDGE__CACHINGEXPIRATION=1:00:00
    ports:
      - 8080:80
    volumes:
      - logs:/logs  