name: Docker Release

on:
  release:
    types:
      - published

env:
  IMAGE_NAME: "towerbridge"
  DOCKERHUB_REGISTRY: "docker.io"
  GITHUB_REGISTRY: "ghcr.io"

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  build:
    name: Build image and push
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Tag Name
        if:  github.event.release.tag_name != ''
        run: echo ${{github.event.release.tag_name}}

      - name: Repository Owner Lower
        id: repository_owner_lower
        uses: ASzc/change-string-case-action@v2
        with:
          string: "${{github.repository_owner}}"
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Install Buildx
        id: docker-buildx
        uses: docker/setup-buildx-action@v1.0.2
        with: 
          version: latest
          
      - name: Docker Meta
        id: docker-meta
        uses: docker/metadata-action@v4.0.1
        with:
          images: |
            ${{env.DOCKERHUB_REGISTRY}}/${{secrets.DOCKER_USERNAME}}/${{env.IMAGE_NAME}}
            ${{env.GITHUB_REGISTRY}}/${{secrets.DOCKER_USERNAME}}/${{env.IMAGE_NAME}}
          flavor: |
            latest=true
          tags: |
            type=sha
      
      - name: Docker Hub login
        id: dockerhub-login
        uses: docker/login-action@v1.4.1
        with: 
          registry: "${{env.DOCKERHUB_REGISTRY}}"
          username: "${{secrets.DOCKERHUB_USERNAME}}"
          password: "${{secrets.DOCKERHUB_PASSWORD}}"

      - name: GHCR login
        id: github-login
        uses: docker/login-action@v1.4.1
        with: 
          registry: "${{env.GITHUB_REGISTRY}}"
          username: "${{github.repository_owner}}"
          password: "${{github.token}}"
      
      - name: Docker build and push
        id: docker-build-push
        uses: docker/build-push-action@v2.3.0
        with:
          context: .
          platforms: linux/arm64,linux/amd64
          push: true
          labels: ${{steps.docker-meta.outputs.labels}}
          tags: ${{steps.docker-meta.outputs.tags}}
          
      - name: Image digest
        run: echo ${{steps.docker-build-push.outputs.digest}}
