name: Docker Release

on:
  release:
    types:
      - published

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  build:
    name: Build image and push
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Tag Name
        if:  github.event.release.tag_name != ''
        run: echo ${{github.event.release.tag_name}}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Install Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.0.2
        with: 
          version: latest
      
      - name: Docker login
        uses: docker/login-action@v1.4.1
        with: 
          registry: "${{secrets.DOCKER_REGISTRY}}"
          username: "${{secrets.DOCKER_USERNAME}}"
          password: "${{secrets.DOCKER_PASSWORD}}"
      
      - name: Docker build and push
        uses: docker/build-push-action@v2.3.0
        with:
          context: .
          platforms: linux/arm,linux/arm64,linux/amd64
          push: true
          tags: |
            "${{secrets.DOCKER_REGISTRY}}/${{secrets.DOCKER_USERNAME}}/towerbridge:latest"
            "${{secrets.DOCKER_REGISTRY}}/${{secrets.DOCKER_USERNAME}}/towerbridge:${{github.event.release.tag_name}}"
        
      - name: Image digest
        run: echo ${{steps.docker_build.outputs.digest}}

      
