name: Docker Release

on:
  release:
    types:
      - published

env:
  IMAGE_NAME: "towerbridge"
  DOCKERHUB_REGISTRY: "docker.io"
  GITHUB_REGISTRY: "ghcr.io"

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  build:
    name: Build image and push
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Tag Name
        if:  github.event.release.tag_name != ''
        run: echo ${{github.event.release.tag_name}}

      - name: Repository Owner Lower
        id: repository_owner_lower
        uses: ASzc/change-string-case-action@v2
        with:
          string: "${{github.repository_owner}}"
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Install Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.0.2
        with: 
          version: latest
      
      - name: Docker Hub login
        id: dockerhub-login
        uses: docker/login-action@v1.4.1
        with: 
          registry: "${{env.DOCKERHUB_REGISTRY}}"
          username: "${{secrets.DOCKERHUB_USERNAME}}"
          password: "${{secrets.DOCKERHUB_PASSWORD}}"

      - name: GHCR login
        id: github-login
        uses: docker/login-action@v1.4.1
        with: 
          registry: "${{env.GITHUB_REGISTRY}}"
          username: "${{github.repository_owner}}"
          password: "${{github.token}}"
      
      - name: Docker build and push
        id: build-push
        uses: docker/build-push-action@v2.3.0
        with:
          context: .
          platforms: linux/arm64,linux/amd64
          push: true
          tags: |
            "${{secrets.DOCKER_REGISTRY}}/${{secrets.DOCKERHUB_USERNAME}}/${{env.IMAGE_NAME}}:latest"
            "${{secrets.DOCKER_REGISTRY}}/${{secrets.DOCKERHUB_USERNAME}}/${{env.IMAGE_NAME}}:${{github.event.release.tag_name}}"
            "${{env.GITHUB_REGISTRY}}/${{steps.repository_owner_lower.outputs.lowercase}}/${{env.IMAGE_NAME}}:latest"
            "${{env.GITHUB_REGISTRY}}/${{steps.repository_owner_lower.outputs.lowercase}}/${{env.IMAGE_NAME}}:${{github.event.release.tag_name}}"
          
      - name: Image digest
        run: echo ${{steps.build-push.outputs.digest}}