name: Docker Release

on:
  release:
    types:
      - published
  
  workflow_dispatch:

env:
  IMAGE_NAME: "towerbridge"
  DOCKERHUB_REGISTRY: "docker.io"
  GITHUB_REGISTRY: "ghcr.io"
  QUAY_REGISTRY: "quay.io"

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  build:
    name: Build image and push
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Repository Owner Lower
        id: repository_owner_lower
        uses: ASzc/change-string-case-action@v2
        with:
          string: "${{github.repository_owner}}"
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Install Buildx
        id: docker-buildx
        uses: docker/setup-buildx-action@v
        with: 
          version: latest

      - name: Docker Metadata
        id: docker-metadata
        uses: docker/metadata-action@v4
        with:
          flavor: |
            latest=auto
          images: |
            ${{env.DOCKERHUB_REGISTRY}}/${{github.repository_owner}}/${{env.IMAGE_NAME}}
            ${{env.GITHUB_REGISTRY}}/${{github.repository_owner}}/${{env.IMAGE_NAME}}
            ${{env.QUAY_REGISTRY}}/${{github.repository_owner}}/${{env.IMAGE_NAME}}
          tags: |
            type=ref,event=tag
            type=sha
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{version}}
      
      - name: Docker Hub login
        id: dockerhub-login
        uses: docker/login-action@v1.4.1
        with: 
          registry: "${{env.DOCKERHUB_REGISTRY}}"
          username: "${{secrets.DOCKERHUB_USERNAME}}"
          password: "${{secrets.DOCKERHUB_PASSWORD}}"
          
      - name: GHCR login
        id: github-login
        uses: docker/login-action@v1.4.1
        with: 
          registry: "${{env.GITHUB_REGISTRY}}"
          username: "${{github.repository_owner}}"
          password: "${{github.token}}"
          
      - name: Quay login
        id: quay-login
        uses: docker/login-action@v1.4.1
        with: 
          registry: "${{env.QUAY_REGISTRY}}"
          username: "${{secrets.QUAY_USERNAME}}"
          password: "${{secrets.QUAY_PASSWORD}}"
      
      - name: Docker Build and Push
        id: docker-build-push
        uses: docker/build-push-action@v2.3.0
        with:
          builder: ${{steps.docker-buildx.outputs.name}}
          context: .
          platforms: linux/arm64,linux/amd64
          push: true
          labels: ${{steps.docker-metadata.outputs.labels}}
          tags: ${{steps.docker-metadata.outputs.tags}}
          
      - name: Docker Hub Description
        id: docker-description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
          repository: ${{secrets.DOCKERHUB_USERNAME}}/${{env.IMAGE_NAME}}
          readme-filepath: ./README.md
        
      - name: Image digest
        run: echo ${{steps.build-push.outputs.digest}}